branches:
  only:
  - master

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

language: r
sudo: required
cache: packages
warnings_are_errors: true
r_check_args: ''

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

r:
  - release
  - devel

r_packages:
  - devtools
  - covr

r_github_packages:
  - jimhester/covr
  - nhejazi/biotmleData

bioc_packages:
  - limma
  - SummarizedExperiment
  - BiocStyle
  - BiocCheck

## coverage
after_success:
  - travis_wait Rscript -e "covr::codecov(line_exclusions = list('R/plots.R'))"
  - R CMD BiocCheck .

notifications:
  email:
    on_success: change
    on_failure: change

