branches:
  only:
  - master
  - develop

language: r
sudo: required
cache: packages
warnings_are_errors: true

r:
  - release
  - devel

env:
  - TEST_DIR=pkg/
  
before_install:
  - cd $TEST_DIR
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_bioc limma
  - ./travis-tool.sh install_bioc_deps

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
