branches:
  only:
  - master

env:
  - TEST_DIR=pkg/

language: r

sudo: required

r:
  - oldrel
  - release
  - devel

before_install:
  - cd $TEST_DIR

warnings_are_errors: true

cache: packages

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
