branches:
  only:
  - master

env:
  global:
  - RGL_USE_NULL=TRUE

language: r
sudo: required
cache: packages

warnings_are_errors: true
r_build_args: '--no-manual'
r_check_args: '--no-build-vignettes --no-manual'

r:
  - bioc-release
  - bioc-devel

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - devtools
  - covr

r_github_packages:
  - r-lib/devtools
  - jimhester/covr
  - nhejazi/biotmleData

bioc_packages:
  - BiocStyle
  - BiocCheck
  - SummarizedExperiment
  - limma

after_success:
  ## coverage
  - travis_wait 60 Rscript -e "covr::codecov(line_exclusions = list('R/plots.R'))"
  - R CMD BiocCheck .

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change

