branches:
  only:
  - master
  - develop

language: r

sudo: required

r:
  - oldrel
  - release
  - devel

env:
  - TEST_DIR=pkg/
  
before_install:
  - cd $TEST_DIR

warnings_are_errors: true

cache: packages

install:
  - ./travis-tool.sh install_bioc limma
  - ./travis-tool.sh install_bioc_deps

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
