branches:
  only:
  - master
  - develop

language: r

sudo: required

cache: packages

warnings_are_errors: true

r:
  - bioc-release
  - bioc-devel
  - release
  - devel

install:
  - ./travis-tool.sh install_bioc limma
  - ./travis-tool.sh install_bioc_deps

## coverage
r_packages:
  - covr

bioc_packages:
  - BiocCheck

after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

notifications:
  email:
    on_success: change
    on_failure: change
